name: CI

on: 
  push:
    branches: 
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  phpunit:
    name: Tests PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip
        coverage: none
      
    - name: Install dependencies
      run: |
        composer install

    - name: Run Testsuite
      run: ./vendor/bin/phpunit
      
  jsunit:
    name: Test Javascript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Yarn install
      run: yarn
    - name: Run Testsuite
      run: yarn test